### ISSUE TITLE
cwebbin vs cweb 4.11

### ISSUE THREAD

**Issue by user706** [ascherer/cwebbin#79]
Hi,

What exactly is the difference between   
a) https://github.com/ascherer/cweb and  
b) https://github.com/ascherer/cwebbin ?

Is `a) cweb` the same as `b) cwebbin` with all patches applied? No wait... it seems like `a) cweb` is the base to which `b) cwebbin` applied patches and changes.

Speaking of patches...  
why does cwebbin have such an ultrastrange way of handling things?  
I'm speaking of the "source drops" and patches.

In today's day and age with git; there seems to be no real reason to have source drops and weird manual steps such as   
_"extract `ctwill.tar.gz` and add the contents of `cweb-4.11.tar.gz`"_ ([link](https://github.com/ascherer/cwebbin/blob/35102977c8efe077e09f5fcf92af380d80bfcdc2/README.md#L26C1-L27C72)) . etc.

So recommendation:  
Why not have a new single repository with a branch `cweb-4.11` and a branch `cwebbin-4.11` (with all patches aready fully applied and results committed)! ?

Then to figure out the differences I can simply do:

```bash
git difftool --dir-diff cweb-4.11 cwebbin-4.11
```

Thanks.

**Comment by ascherer** [comment]
> What exactly is the difference between a) https://github.com/ascherer/cweb and b) https://github.com/ascherer/cwebbin ?

You figured that one out yourself. I did, in fact, transfer quite a lot of stuff from CWEBbin to CWEB when I started to maintain the upstream code of **CWEB 4**. However, the CWEBbin extensions—including, but not limited to, the integration into TeX Live—do not fit well in CWEB proper.

> Speaking of patches... why does cwebbin have such an ultrastrange way of handling things? I'm speaking of the "source drops" and patches.

Because. I started to work on CWEB—porting it to the Commodore Amiga in **early 1993**—more than thirty years ago, a long time before **Git** became a thing. (I used RCS, Subversion, and Perforce at one time or another, before committing [_sic!_] to Git.)

> _"extract `ctwill.tar.gz` and add the contents of `cweb-4.11.tar.gz`"_

Yep, CTWILL is a serious problem in and of itself. The form in which it is presented in CWEBbin/TeX Live is a really long way from the “original” tarball somewhere on the Stanford servers (see the archived https://github.com/ascherer/ctwill project and its various branches for details).

> So recommendation: Why not have a new single repository with a branch `cweb-4.11` and a branch `cwebbin-4.11` (with all patches aready fully applied and results committed)! ?

Feel free to do so! In fact, after the recent releases of **CWEB 4.11**, **CWEBbin 2023.3**, and **pwebmac 4.11**, I am considering to hand over the future development of, say, **CWEB 5** to someone else. At this time, I am waiting for the release of **TeX Live 2024** in order to publish updated versions of the [knuth-pdf](https://ctan.org/pkg/knuth-pdf) and [knuth-hint](https://ctan.org/pkg/knuth-hint) packages on CTAN. After that I might call it quits.

**Comment by ascherer** [comment]
> all patches aready fully applied and results committed
See [CWEB in TeX Live](https://github.com/TeX-Live/texlive-source/tree/trunk/texk/web2c/cwebdir) and all `*-w2c.*` files for the final final rresults.

**Comment by ascherer** [comment]
> Speaking of patches... why does cwebbin have such an ultrastrange way of handling things? I'm speaking of the "source drops" and patches.

In general, I let [`debbuild`/`rpmbuild`](https://github.com/ascherer/cwebbin/blob/master/cwebbin.spec#L41) do the job of unpacking the source drops and applying the patches.
